version: "3.8"
services:
    mint_ui:
        build:
            context: .
            dockerfile: Dev.dockerfile
        volumes:
            - ".:/app"
            - "node_modules:/app/node_modules"
        ports:
            - "80:80"
            - "9000:9000"
volumes:
    node_modules: